title: lxz.nl # The title of the blog
author: Lex # Your name 
email: contact@lxz.nl # your email shown in the footer
url: https://www.lxz.nl/ # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  lxz.nl
favicon: "./favicon.ico" # set the favicon of the site 

show_excerpts: false # set to true to show excerpts on the homepage
# google_analytics: UA-138300702-1
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: # "https://avatars3.githubusercontent.com/u/27029242?s=460&v=4"  avatar in about page
  about_you: '?' # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Blog" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    # twitter: 
    github:  lxz81
    # rss: RSS
    # dribbble: 
    facebook: lexciting
    # flickr:   
    instagram: lexciting
    linkedin: lexciting
    # pinterest: 
    # youtube: 
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 
    # reddit: aeren108

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# Build settings
theme: moving # note, please use huangyz0918/moving if you want to publish to Github Pages.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
